/**
 * Frontend contracts for the future Express API.
 *
 * MongoDB ObjectIds are serialized as strings at the HTTP boundary. The
 * development fixtures use the same shape so the visual product can work
 * before a backend is implemented.
 */
export type JournalMode = "vault" | "future_self";

export interface ApiResponse<T> {
  success: boolean;
  data: T;
  message?: string;
}

export interface ApiErrorBody {
  success: false;
  message: string;
  code?: string;
}

export interface User {
  id: string;
  name: string;
  email: string;
  role: "user" | "admin";
  createdAt: Date;
}

export interface Collection {
  id: string;
  userId: string;
  name: string;
  isAutoGenerated: boolean;
  createdAt: Date;
}

export interface JournalEntry {
  id: string;
  userId: string;
  audioUrl: string | null;
  audioKey: string;
  transcript: string | null;
  durationSec: number;
  createdAt: Date;
  mood: string | null;
  collectionId: string | null;
  ambience: string | null;
  title: string | null;
  mode: JournalMode;
  sealDate: Date | null;
  unlockDate: Date | null;
  encryptedAudioKey: string | null;
  encrypted: boolean;
  isUnlocked: boolean;
}

export interface CreateJournalEntryInput {
  audioKey: string;
  audioUrl: string;
  transcript: string | null;
  durationSec: number;
  ambience: string;
  mode: JournalMode;
  sealDate?: Date;
  unlockDate?: Date;
  encryptedAudioKey?: string | null;
  encrypted?: boolean;
}

export interface UpdateJournalEntryInput {
  mood?: string | null;
  collectionId?: string | null;
  title?: string | null;
}

export interface MetadataSuggestion {
  mood: string | null;
  collection: string | null;
  title: string | null;
}

export interface Insight {
  id: string;
  userId: string;
  periodMonth: string;
  topWords: string[];
  avgDurationSec: number;
  generatedObservation: string | null;
  createdAt: Date;
}

export interface AudioAsset {
  id: string;
  userId: string;
  key: string;
  url: string;
  contentType: string;
  originalName: string;
  createdAt: Date;
}

export interface ArchiveDownload {
  url: string;
  filename: string;
}
