CREATE TABLE `collections` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(128) NOT NULL,
	`isAutoGenerated` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `collections_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `echoes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`audioUrl` text,
	`audioKey` text NOT NULL,
	`transcript` text,
	`durationSec` float NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`mood` varchar(64),
	`collectionId` int,
	`ambience` varchar(64) DEFAULT 'silence',
	`title` text,
	`mode` enum('vault','future_self') NOT NULL DEFAULT 'vault',
	`sealDate` timestamp,
	`unlockDate` timestamp,
	`encryptedAudioKey` text,
	`encrypted` boolean NOT NULL DEFAULT false,
	CONSTRAINT `echoes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `insightSnapshots` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`periodMonth` varchar(7) NOT NULL,
	`topWords` text NOT NULL,
	`avgDurationSec` float DEFAULT 0,
	`generatedObservation` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `insightSnapshots_id` PRIMARY KEY(`id`)
);
