import { int, mysqlEnum, mysqlTable, text, timestamp, varchar, bigint, boolean, float } from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 */
export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * Collections — named "rooms" for organizing echoes.
 */
export const collections = mysqlTable("collections", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  name: varchar("name", { length: 128 }).notNull(),
  isAutoGenerated: boolean("isAutoGenerated").default(false).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Collection = typeof collections.$inferSelect;
export type InsertCollection = typeof collections.$inferInsert;

/**
 * Echoes — the core data model for voice recordings.
 */
export const echoes = mysqlTable("echoes", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  audioUrl: text("audioUrl"),
  audioKey: text("audioKey").notNull(),
  transcript: text("transcript"),
  durationSec: float("durationSec").notNull().default(0),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  mood: varchar("mood", { length: 64 }),
  collectionId: int("collectionId"),
  ambience: varchar("ambience", { length: 64 }).default("silence"),
  title: text("title"),
  mode: mysqlEnum("mode", ["vault", "future_self"]).default("vault").notNull(),
  sealDate: timestamp("sealDate"),
  unlockDate: timestamp("unlockDate"),
  encryptedAudioKey: text("encryptedAudioKey"),
  encrypted: boolean("encrypted").default(false).notNull(),
});

export type Echo = typeof echoes.$inferSelect;
export type InsertEcho = typeof echoes.$inferInsert;

/**
 * Insight snapshots — monthly qualitative summaries.
 */
export const insightSnapshots = mysqlTable("insightSnapshots", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  periodMonth: varchar("periodMonth", { length: 7 }).notNull(), // e.g. "2026-07"
  topWords: text("topWords").notNull(), // JSON array of strings
  avgDurationSec: float("avgDurationSec").default(0),
  generatedObservation: text("generatedObservation"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type InsightSnapshot = typeof insightSnapshots.$inferSelect;
export type InsertInsightSnapshot = typeof insightSnapshots.$inferInsert;
