import { useState } from "react";
import { useAsyncResource } from "@/hooks/useAsyncResource";
import { collectionService } from "@/services/collectionService";
import { journalService } from "@/services/journalService";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { FolderOpen, Plus, X, Sparkle } from "lucide-react";
import { toast } from "sonner";
import { ScrollReveal } from "@/components/ScrollReveal";
import { ParallaxTilt } from "@/components/ParallaxTilt";

export default function Collections() {
  const collections = useAsyncResource(() => collectionService.list(), []);
  const [newName, setNewName] = useState("");
  const [showCreate, setShowCreate] = useState(false);
  const [selectedCollection, setSelectedCollection] = useState<string | null>(null);

  const echoesByCollection = useAsyncResource(
    () => journalService.listByCollection(selectedCollection!),
    [selectedCollection],
    selectedCollection !== null,
  );

  const handleCreate = async () => {
    if (!newName.trim()) return;
    try {
      await collectionService.create(newName.trim());
      collections.reload();
      setNewName("");
      setShowCreate(false);
      toast.success("Collection created.");
    } catch {
      toast.error("Failed to create collection.");
    }
  };

  const handleDelete = async (id: string) => {
    try {
      await collectionService.remove(id);
      if (selectedCollection === id) setSelectedCollection(null);
      collections.reload();
      echoesByCollection.reload();
      toast.success("Collection removed.");
    } catch {
      toast.error("Failed to delete collection.");
    }
  };

  if (collections.isLoading) {
    return (
      <div className="flex items-center justify-center min-h-[60vh]">
        <div className="w-6 h-6 border-2 border-amber/20 border-t-amber/60 rounded-full animate-spin" />
      </div>
    );
  }

  const currentCollection = collections.data?.find(c => c.id === selectedCollection);

  return (
    <div className="max-w-lg mx-auto px-4 pt-8">
      <div className="flex items-center justify-between mb-10">
        <h1 className="font-serif-sacred text-2xl text-foreground tracking-wide">Collections</h1>
        <Button
          variant="outline"
          size="sm"
          onClick={() => setShowCreate(true)}
          className="glass-warm text-amber hover:text-amber hover:bg-amber/10 border-amber/20 transition-all duration-300"
        >
          <Plus className="h-3.5 w-3.5 mr-1" />
          New
        </Button>
      </div>

      {/* Collection grid */}
      <div className="grid grid-cols-2 gap-4 mb-10">
        {collections.data?.map((col, i) => {
          const echoCount = echoesByCollection.data?.length || 0;
          return (
            <ScrollReveal key={col.id} delay={i * 60}>
            <ParallaxTilt>
            <div
              onClick={() => setSelectedCollection(selectedCollection === col.id ? null : col.id)}
              className={`relative p-5 rounded-xl border cursor-pointer transition-all duration-500 group ${
                selectedCollection === col.id
                  ? "glass-warm glow-amber border-amber/25"
                  : "glass hover:border-amber/15 hover:bg-charcoal-lighter/40"
              }`}
              style={{ animationDelay: `${i * 0.06}s` }}
            >
              <div className="flex items-center justify-between mb-3">
                <h3 className="text-sm font-medium text-foreground/90 font-serif-sacred tracking-wide">{col.name}</h3>
                <span className="text-xs text-muted-foreground/50 tabular-nums">{echoCount}</span>
              </div>
              <div className="flex items-center justify-between">
                <p className="text-[10px] text-muted-foreground/40 tracking-wider uppercase">
                  {col.isAutoGenerated ? "Auto" : "Custom"}
                </p>
                {!col.isAutoGenerated && (
                  <button
                    onClick={(e) => { e.stopPropagation(); handleDelete(col.id); }}
                    className="text-muted-foreground/30 hover:text-destructive/70 transition-colors duration-300"
                  >
                    <X className="h-3 w-3" />
                  </button>
                )}
              </div>
              {/* Subtle glow when selected */}
              {selectedCollection === col.id && (
                <div className="absolute inset-0 rounded-xl bg-amber/3 pointer-events-none" />
              )}
            </div>
            </ParallaxTilt>
            </ScrollReveal>
          );
        })}
      </div>

      {/* Echoes in selected collection */}
      {selectedCollection && currentCollection && (
        <div className="border-t border-border/15 pt-6 sacred-reveal">
          <h3 className="font-serif-sacred text-sm text-foreground/80 mb-4 tracking-wide">
            In "{currentCollection.name}"
          </h3>
          {echoesByCollection.isLoading ? (
            <p className="text-sm text-muted-foreground/60 font-light">Loading...</p>
          ) : echoesByCollection.data && echoesByCollection.data.length > 0 ? (
            <div className="space-y-2.5">
              {echoesByCollection.data.map(echo => (
                <div key={echo.id} className="glass rounded-lg p-4 transition-all duration-300 hover:bg-charcoal-lighter/40">
                  <p className="text-sm text-foreground/90 font-light">{echo.title || "Untitled"}</p>
                  <p className="text-xs text-muted-foreground/50 mt-1.5 line-clamp-1 font-light">
                    {echo.transcript || "No transcript"}
                  </p>
                </div>
              ))}
            </div>
          ) : (
            <p className="text-sm text-muted-foreground/50 font-light">No echoes in this collection yet.</p>
          )}
        </div>
      )}

      {/* Create collection modal */}
      {showCreate && (
        <div className="fixed inset-0 z-50 bg-void/80 backdrop-blur-md flex items-center justify-center p-4">
          <div className="glass-strong rounded-2xl p-7 max-w-sm w-full sacred-reveal glow-inner">
            <h3 className="font-serif-sacred text-lg text-foreground mb-5 tracking-wide">New collection</h3>
            <Input
              value={newName}
              onChange={(e) => setNewName(e.target.value)}
              placeholder="Name your room..."
              className="bg-charcoal/40 border-border/40 text-foreground placeholder:text-muted-foreground/40 mb-5 focus:border-amber/40 transition-colors duration-300"
              onKeyDown={(e) => e.key === "Enter" && handleCreate()}
            />
            <div className="flex gap-3">
              <Button
                variant="outline"
                onClick={() => setShowCreate(false)}
                className="flex-1 border-border/40 text-muted-foreground hover:border-amber/20 transition-all duration-300"
              >
                Cancel
              </Button>
              <Button
                onClick={handleCreate}
                className="flex-1 bg-amber/80 hover:bg-amber text-primary-foreground shadow-lg shadow-amber/10 transition-all duration-300"
                disabled={!newName.trim()}
              >
                Create
              </Button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
