import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { FolderOpen, Plus, X } from "lucide-react";
import { toast } from "sonner";

export default function Collections() {
  const collections = trpc.collections.list.useQuery(undefined);
  const createMutation = trpc.collections.create.useMutation();
  const deleteMutation = trpc.collections.delete.useMutation();
  const [newName, setNewName] = useState("");
  const [showCreate, setShowCreate] = useState(false);
  const [selectedCollection, setSelectedCollection] = useState<number | null>(null);

  const echoesByCollection = trpc.echoes.byCollection.useQuery(
    { collectionId: selectedCollection! },
    { enabled: selectedCollection !== null }
  );

  const handleCreate = async () => {
    if (!newName.trim()) return;
    try {
      await createMutation.mutateAsync({ name: newName.trim() });
      setNewName("");
      setShowCreate(false);
      toast.success("Collection created.");
    } catch {
      toast.error("Failed to create collection.");
    }
  };

  const handleDelete = async (id: number) => {
    try {
      await deleteMutation.mutateAsync({ id });
      if (selectedCollection === id) setSelectedCollection(null);
      toast.success("Collection removed.");
    } catch {
      toast.error("Failed to delete collection.");
    }
  };

  if (collections.isLoading) {
    return (
      <div className="flex items-center justify-center min-h-[60vh]">
        <div className="w-6 h-6 border-2 border-amber/30 border-t-amber rounded-full animate-spin" />
      </div>
    );
  }

  const currentCollection = collections.data?.find(c => c.id === selectedCollection);

  return (
    <div className="max-w-lg mx-auto px-4 pt-8">
      <div className="flex items-center justify-between mb-8">
        <h1 className="font-serif-display text-2xl text-foreground">Collections</h1>
        <Button
          variant="outline"
          size="sm"
          onClick={() => setShowCreate(true)}
          className="border-amber/30 text-amber hover:bg-amber/10"
        >
          <Plus className="h-3.5 w-3.5 mr-1" />
          New
        </Button>
      </div>

      {/* Collection grid */}
      <div className="grid grid-cols-2 gap-3 mb-8">
        {collections.data?.map(col => {
          const echoCount = echoesByCollection.data?.length || 0;
          return (
            <div
              key={col.id}
              onClick={() => setSelectedCollection(selectedCollection === col.id ? null : col.id)}
              className={`p-4 rounded-xl border cursor-pointer transition-all ${
                selectedCollection === col.id
                  ? "bg-amber/10 border-amber/30"
                  : "bg-charcoal-light border-border/30 hover:border-border/50"
              }`}
            >
              <div className="flex items-center justify-between mb-2">
                <h3 className="text-sm font-medium text-foreground">{col.name}</h3>
                <span className="text-xs text-muted-foreground">{echoCount}</span>
              </div>
              <div className="flex items-center justify-between">
                <p className="text-[10px] text-muted-foreground/60">
                  {col.isAutoGenerated ? "Auto" : "Custom"}
                </p>
                {!col.isAutoGenerated && (
                  <button
                    onClick={(e) => { e.stopPropagation(); handleDelete(col.id); }}
                    className="text-muted-foreground/40 hover:text-destructive transition-colors"
                  >
                    <X className="h-3 w-3" />
                  </button>
                )}
              </div>
            </div>
          );
        })}
      </div>

      {/* Echoes in selected collection */}
      {selectedCollection && currentCollection && (
        <div className="border-t border-border/30 pt-6">
          <h3 className="text-sm font-medium text-foreground mb-4">
            In "{currentCollection.name}"
          </h3>
          {echoesByCollection.isLoading ? (
            <p className="text-sm text-muted-foreground">Loading...</p>
          ) : echoesByCollection.data && echoesByCollection.data.length > 0 ? (
            <div className="space-y-2">
              {echoesByCollection.data.map(echo => (
                <div key={echo.id} className="p-3 rounded-lg bg-charcoal-lighter border border-border/20">
                  <p className="text-sm text-foreground">{echo.title || "Untitled"}</p>
                  <p className="text-xs text-muted-foreground mt-1 line-clamp-1">
                    {echo.transcript || "No transcript"}
                  </p>
                </div>
              ))}
            </div>
          ) : (
            <p className="text-sm text-muted-foreground">No echoes in this collection yet.</p>
          )}
        </div>
      )}

      {/* Create collection modal */}
      {showCreate && (
        <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="bg-charcoal-light border border-border rounded-2xl p-6 max-w-sm w-full">
            <h3 className="font-serif-display text-lg text-foreground mb-4">New collection</h3>
            <Input
              value={newName}
              onChange={(e) => setNewName(e.target.value)}
              placeholder="Name your room..."
              className="bg-charcoal border-border text-foreground mb-4"
              onKeyDown={(e) => e.key === "Enter" && handleCreate()}
            />
            <div className="flex gap-3">
              <Button
                variant="outline"
                onClick={() => setShowCreate(false)}
                className="flex-1 border-border text-muted-foreground"
              >
                Cancel
              </Button>
              <Button
                onClick={handleCreate}
                className="flex-1 bg-amber/90 hover:bg-amber text-primary-foreground"
                disabled={!newName.trim()}
              >
                Create
              </Button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
