import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { publicProcedure, protectedProcedure, router } from "./_core/trpc";
import { TRPCError } from "@trpc/server";
import { z } from "zod";
import { eq, desc, and } from "drizzle-orm";
import {
  createEcho, getEchoById, getEchoesByUserId, getRecentEchoes,
  getEchoesByMode, getEchoesByCollection, updateEcho,
  getCollectionsByUserId, createCollection, deleteCollection,
  getInsightByUserIdAndPeriod, createOrUpdateInsight, getUserInsights,
  getAllUserData, computeIsUnlocked, getDb,
} from "./db";
import { echoes, collections, insightSnapshots, users } from "../drizzle/schema";
import { storagePut, storageGet } from "./storage";
import { transcribeAudio } from "./_core/voiceTranscription";
import { invokeLLM } from "./_core/llm";
import { promises as fs } from "fs";
import { exec } from "child_process";
import { promisify } from "util";
const execAsync = promisify(exec);

const DEFAULT_COLLECTIONS = [
  "Life", "Letters", "Dreams", "Ideas", "Poetry", "Faith", "Music", "Coding",
];

export const appRouter = router({
  system: systemRouter,
  auth: router({
    me: publicProcedure.query(opts => opts.ctx.user),
    logout: publicProcedure.mutation(({ ctx }) => {
      const cookieOptions = getSessionCookieOptions(ctx.req);
      ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 });
      return { success: true } as const;
    }),
  }),

  // ─── Collections ───
  collections: router({
    list: protectedProcedure.query(async ({ ctx }) => {
      const cols = await getCollectionsByUserId(ctx.user.id);
      if (cols.length === 0) {
        // Seed default collections
        for (const name of DEFAULT_COLLECTIONS) {
          await createCollection({ userId: ctx.user.id, name, isAutoGenerated: true });
        }
        return getCollectionsByUserId(ctx.user.id);
      }
      return cols;
    }),
    create: protectedProcedure
      .input(z.object({ name: z.string().min(1).max(128) }))
      .mutation(async ({ ctx, input }) => {
        return createCollection({ userId: ctx.user.id, name: input.name, isAutoGenerated: false });
      }),
    delete: protectedProcedure
      .input(z.object({ id: z.number() }))
      .mutation(async ({ ctx, input }) => {
        await deleteCollection(input.id, ctx.user.id);
        return { success: true };
      }),
  }),

  // ─── Echoes ───
  echoes: router({
    list: protectedProcedure.query(async ({ ctx }) => {
      const items = await getEchoesByUserId(ctx.user.id);
      return items.map(e => ({ ...e, isUnlocked: computeIsUnlocked(e) }));
    }),
    recent: protectedProcedure
      .input(z.object({ limit: z.number().min(1).max(20).default(5) }))
      .query(async ({ ctx, input }) => {
        const items = await getRecentEchoes(ctx.user.id, input.limit);
        return items.map(e => ({ ...e, isUnlocked: computeIsUnlocked(e) }));
      }),
    byMode: protectedProcedure
      .input(z.object({ mode: z.enum(["vault", "future_self"]) }))
      .query(async ({ ctx, input }) => {
        const items = await getEchoesByMode(ctx.user.id, input.mode);
        return items.map(e => ({ ...e, isUnlocked: computeIsUnlocked(e) }));
      }),
    byCollection: protectedProcedure
      .input(z.object({ collectionId: z.number() }))
      .query(async ({ ctx, input }) => {
        const items = await getEchoesByCollection(input.collectionId, ctx.user.id);
        return items.map(e => ({ ...e, isUnlocked: computeIsUnlocked(e) }));
      }),
    get: protectedProcedure
      .input(z.object({ id: z.number() }))
      .query(async ({ ctx, input }) => {
        const echo = await getEchoById(input.id, ctx.user.id);
        if (!echo) throw new TRPCError({ code: "NOT_FOUND", message: "Echo not found" });
        // Server-enforced lock
        if (echo.mode === 'future_self' && !computeIsUnlocked(echo)) {
          return { ...echo, isUnlocked: false, audioUrl: null, transcript: null };
        }
        return { ...echo, isUnlocked: true };
      }),
    create: protectedProcedure
      .input(z.object({
        audioKey: z.string(),
        audioUrl: z.string(),
        transcript: z.string().nullable(),
        durationSec: z.number(),
        ambience: z.string().default("silence"),
        mode: z.enum(["vault", "future_self"]).default("vault"),
        sealDate: z.date().optional(),
        unlockDate: z.date().optional(),
        encryptedAudioKey: z.string().nullable().optional(),
        encrypted: z.boolean().default(false),
      }))
      .mutation(async ({ ctx, input }) => {
        const echo = await createEcho({
          userId: ctx.user.id,
          audioKey: input.audioKey,
          audioUrl: input.audioUrl,
          transcript: input.transcript,
          durationSec: input.durationSec,
          ambience: input.ambience,
          mode: (input.mode || "vault") as "vault" | "future_self",
          sealDate: input.sealDate || null,
          unlockDate: input.unlockDate || null,
          encryptedAudioKey: input.encryptedAudioKey || null,
          encrypted: input.encrypted,
        });
        return { ...echo, isUnlocked: computeIsUnlocked(echo) };
      }),
    update: protectedProcedure
      .input(z.object({
        id: z.number(),
        mood: z.string().nullable().optional(),
        collectionId: z.number().nullable().optional(),
        title: z.string().nullable().optional(),
      }))
      .mutation(async ({ ctx, input }) => {
        await updateEcho(input.id, ctx.user.id, {
          mood: input.mood,
          collectionId: input.collectionId,
          title: input.title,
        });
        return { success: true };
      }),
    suggestMoodAndCollection: protectedProcedure
      .input(z.object({ transcript: z.string() }))
      .mutation(async ({ ctx, input }) => {
        const response = await invokeLLM({
          model: "gpt-4.1-mini",
          messages: [
            {
              role: "system",
              content: `You are a gentle voice journal assistant. Analyze the transcript and suggest:
1. One mood word (single lowercase word like "tender", "restless", "hopeful", "grateful", "weary", "curious", "grief", "joy", "wonder", "doubt")
2. One collection name from: Life, Letters, Dreams, Ideas, Poetry, Faith, Music, Coding
3. A short title (3-6 words) for the entry

Respond ONLY with valid JSON: {"mood": "word", "collection": "CollectionName", "title": "short title"}`
            },
            { role: "user", content: input.transcript },
          ],
        });
        const rawContent = response.choices[0]?.message?.content;
        const content = typeof rawContent === 'string' ? rawContent : "{}";
        try {
          const parsed = JSON.parse(content);
          return {
            mood: parsed.mood || null,
            collection: parsed.collection || null,
            title: parsed.title || null,
          };
        } catch {
          return { mood: null, collection: null, title: null };
        }
      }),
    transcribe: protectedProcedure
      .input(z.object({ audioUrl: z.string() }))
      .mutation(async ({ ctx, input }) => {
        const result = await transcribeAudio({ audioUrl: input.audioUrl, language: "en" });
        if ('error' in result) {
          throw new TRPCError({ code: "BAD_REQUEST", message: result.error });
        }
        return { transcript: result.text || "" };
      }),
  }),

  // ─── Insights ───
  insights: router({
    get: protectedProcedure
      .input(z.object({ periodMonth: z.string().regex(/^\d{4}-\d{2}$/) }))
      .query(async ({ ctx, input }) => {
        const existing = await getInsightByUserIdAndPeriod(ctx.user.id, input.periodMonth);
        if (existing) {
          const topWords = JSON.parse(existing.topWords);
          return {
            ...existing,
            topWords,
          };
        }
        // Generate new insight
        const echoes = await getEchoesByUserId(ctx.user.id);
        if (echoes.length === 0) {
          return null;
        }

        // Extract all transcript words
        const allText = echoes.map(e => e.transcript).filter(Boolean).join(" ");
        const words = allText.toLowerCase().replace(/[^a-z\s]/g, '').split(/\s+/).filter(w => w.length > 3);
        const wordFreq: Record<string, number> = {};
        words.forEach(w => { wordFreq[w] = (wordFreq[w] || 0) + 1; });
        const sortedWords = Object.entries(wordFreq)
          .sort(([, a], [, b]) => b - a)
          .slice(0, 15)
          .map(([word]) => word);

        const avgDuration = echoes.reduce((sum, e) => sum + e.durationSec, 0) / echoes.length;

        // Generate observation
        const response = await invokeLLM({
          model: "gpt-4.1-mini",
          messages: [
            {
              role: "system",
              content: `You are the voice of a personal journal app called Echoes. Write ONE short, poetic observation sentence about the user's recent recordings. 

Style rules:
- Second person ("you")
- Literary, quiet, intimate tone
- Reference patterns in word choice, pacing, or emotional texture
- Never mention numbers, statistics, or data
- Maximum 2 sentences
- Do NOT give advice. Just observe.

Examples of good observations:
- "You spoke more slowly this month, as if the words needed more room to land."
- "The same quiet longing keeps returning — tender, but not yet resolved."
- "Your words this month leaned toward the future, toward things not yet built."

Respond ONLY with the observation text, no quotes, no preamble.`
            },
            {
              role: "user",
              content: `Here are the user's most frequently used words: ${sortedWords.join(", ")}
Their recordings cover topics like: ${echoes.slice(0, 10).map(e => e.transcript?.substring(0, 80)).filter(Boolean).join(" | ")}`
            },
          ],
        });
        const rawObs = response.choices[0]?.message?.content;
        const observation = typeof rawObs === 'string' ? rawObs : "";

        const snapshot = await createOrUpdateInsight({
          userId: ctx.user.id,
          periodMonth: input.periodMonth,
          topWords: JSON.stringify(sortedWords),
          avgDurationSec: avgDuration,
          generatedObservation: observation,
        });

        return {
          ...snapshot,
          topWords: sortedWords,
        };
      }),
  }),

  // ─── Archive Export ───
  archive: router({
    export: protectedProcedure.mutation(async ({ ctx }) => {
      const data = await getAllUserData(ctx.user.id);
      const tmpDir = `/tmp/echoes-export-${ctx.user.id}-${Date.now()}`;
      await fs.mkdir(tmpDir, { recursive: true });

      // Save audio files
      const audioFiles: string[] = [];
      for (const echo of data.echoes) {
        if (echo.audioUrl) {
          try {
            const presignedUrl = await storageGet(echo.audioKey);
            const resp = await fetch(presignedUrl.url);
            const buffer = await resp.arrayBuffer();
            const filename = `echo-${echo.id}-${echo.createdAt.getTime()}.webm`;
            await fs.writeFile(`${tmpDir}/audio/${filename}`, Buffer.from(buffer));
            audioFiles.push(filename);
          } catch (err) {
            console.warn(`Failed to export echo ${echo.id}:`, err);
          }
        }
      }

      // Save metadata
      const metadata = {
        exportedAt: new Date().toISOString(),
        user: { id: ctx.user.id, name: ctx.user.name, email: ctx.user.email },
        echoes: data.echoes.map(e => ({
          id: e.id,
          transcript: e.transcript,
          mood: e.mood,
          ambience: e.ambience,
          title: e.title,
          mode: e.mode,
          durationSec: e.durationSec,
          createdAt: e.createdAt.toISOString(),
          sealDate: e.sealDate?.toISOString() || null,
          unlockDate: e.unlockDate?.toISOString() || null,
          audioFile: e.audioUrl ? audioFiles.find(f => f.includes(`echo-${e.id}`)) || null : null,
        })),
        collections: data.collections,
      };

      await fs.mkdir(`${tmpDir}/audio`, { recursive: true });
      await fs.writeFile(`${tmpDir}/metadata.json`, JSON.stringify(metadata, null, 2));

      // Create zip
      const zipPath = `/tmp/echoes-archive-${ctx.user.id}-${Date.now()}.zip`;
      await execAsync(`cd ${tmpDir} && zip -r ${zipPath} .`);

      // Upload zip to storage
      const zipBuffer = await fs.readFile(zipPath);
      const fileKey = `${ctx.user.id}-exports/echoes-archive-${Date.now()}.zip`;
      const { url, key } = await storagePut(fileKey, zipBuffer, "application/zip");

      // Cleanup
      await execAsync(`rm -rf ${tmpDir} ${zipPath}`);

      return { url, key, filename: `echoes-archive-${Date.now()}.zip` };
    }),
  }),

  // ─── Account ───
  account: router({
    delete: protectedProcedure.mutation(async ({ ctx }) => {
      const db = await (await import("./db")).getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" });
      const { sql } = await import("drizzle-orm");
      // Delete user data
      await db.delete(echoes).where(eq(echoes.userId, ctx.user.id));
      await db.delete(collections).where(eq(collections.userId, ctx.user.id));
      await db.delete(insightSnapshots).where(eq(insightSnapshots.userId, ctx.user.id));
      await db.delete(users).where(eq(users.id, ctx.user.id));
      // Clear cookie
      const cookieOptions = getSessionCookieOptions(ctx.req);
      ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 });
      return { success: true };
    }),
  }),
});

export type AppRouter = typeof appRouter;
