import mongoose from "mongoose";

/** Collection schema stub — a named room for organizing journal entries. */
export const collectionSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
  name: String,
  isAutoGenerated: { type: Boolean, default: false },
}, { timestamps: true });

// TODO: Choose validation and a userId + name uniqueness strategy.
