import type {
  Collection,
  CreateJournalEntryInput,
  Insight,
  JournalEntry,
  JournalMode,
  MetadataSuggestion,
  UpdateJournalEntryInput,
  User,
} from "@/types/api";

/**
 * DEVELOPMENT FIXTURES ONLY
 *
 * This in-memory store deliberately does not persist data or emulate MongoDB.
 * It exists to keep the completed product UI navigable while the learner builds
 * the real Express, MongoDB, storage, and AI layers.
 */
export const developmentUser: User = {
  id: "dev-user-echoes",
  name: "Echoes Developer",
  email: "developer@local.echoes",
  role: "user",
  createdAt: new Date("2026-01-01T00:00:00.000Z"),
};

const DEFAULT_COLLECTION_NAMES = ["Life", "Letters", "Dreams", "Ideas", "Poetry", "Faith", "Music", "Coding"];

let collections: Collection[] = DEFAULT_COLLECTION_NAMES.map((name) => ({
  id: `fixture-collection-${name.toLowerCase()}`,
  userId: developmentUser.id,
  name,
  isAutoGenerated: true,
  createdAt: new Date("2026-01-01T00:00:00.000Z"),
}));

let entries: JournalEntry[] = [];

function fixtureId(prefix: string) {
  return typeof crypto !== "undefined" && "randomUUID" in crypto
    ? `${prefix}-${crypto.randomUUID()}`
    : `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2)}`;
}

function computeIsUnlocked(mode: JournalMode, unlockDate: Date | null) {
  return mode !== "future_self" || !unlockDate || Date.now() >= unlockDate.getTime();
}

export function listFixtureCollections() {
  return [...collections];
}

export function createFixtureCollection(name: string) {
  const collection: Collection = {
    id: fixtureId("collection"),
    userId: developmentUser.id,
    name,
    isAutoGenerated: false,
    createdAt: new Date(),
  };
  collections = [collection, ...collections];
  return collection;
}

export function removeFixtureCollection(id: string) {
  collections = collections.filter((collection) => collection.id !== id || collection.isAutoGenerated);
  entries = entries.map((entry) => entry.collectionId === id ? { ...entry, collectionId: null } : entry);
}

export function listFixtureEntries() {
  return [...entries].sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime()).map((entry) => ({
    ...entry,
    isUnlocked: computeIsUnlocked(entry.mode, entry.unlockDate),
  }));
}

export function getFixtureEntry(id: string) {
  const entry = entries.find((item) => item.id === id);
  if (!entry) return null;

  const isUnlocked = computeIsUnlocked(entry.mode, entry.unlockDate);
  return isUnlocked ? { ...entry, isUnlocked } : { ...entry, isUnlocked, audioUrl: null, transcript: null };
}

export function createFixtureEntry(input: CreateJournalEntryInput) {
  const entry: JournalEntry = {
    id: fixtureId("entry"),
    userId: developmentUser.id,
    audioKey: input.audioKey,
    audioUrl: input.audioUrl,
    transcript: input.transcript,
    durationSec: input.durationSec,
    createdAt: new Date(),
    mood: null,
    collectionId: null,
    ambience: input.ambience,
    title: null,
    mode: input.mode,
    sealDate: input.sealDate ?? null,
    unlockDate: input.unlockDate ?? null,
    encryptedAudioKey: input.encryptedAudioKey ?? null,
    encrypted: input.encrypted ?? false,
    isUnlocked: computeIsUnlocked(input.mode, input.unlockDate ?? null),
  };
  entries = [entry, ...entries];
  return entry;
}

export function updateFixtureEntry(id: string, input: UpdateJournalEntryInput) {
  const existing = entries.find((entry) => entry.id === id);
  if (!existing) throw new Error("The fixture entry was not found.");

  const updated = { ...existing, ...input };
  entries = entries.map((entry) => entry.id === id ? updated : entry);
  return updated;
}

export function fixtureTranscription() {
  return {
    transcript: "This is a local development transcription fixture. Connect POST /api/journal-entries/:id/transcribe to a provider when you are ready.",
  };
}

export function fixtureMetadataSuggestion(): MetadataSuggestion {
  return {
    mood: "reflective",
    collection: "Life",
    title: "A quiet echo",
  };
}

export function getFixtureInsight(_periodMonth: string): Insight | null {
  // TODO: Build MongoDB aggregation and the optional AI observation service.
  return null;
}

export function exportFixtureArchive() {
  return JSON.stringify({
    notice: "DEVELOPMENT FIXTURE — build GET /api/archive before producing a real archive.",
    generatedAt: new Date().toISOString(),
    entries: listFixtureEntries(),
    collections: listFixtureCollections(),
  }, null, 2);
}

export function deleteFixtureAccountData() {
  entries = [];
  collections = DEFAULT_COLLECTION_NAMES.map((name) => ({
    id: `fixture-collection-${name.toLowerCase()}`,
    userId: developmentUser.id,
    name,
    isAutoGenerated: true,
    createdAt: new Date("2026-01-01T00:00:00.000Z"),
  }));
}
